### ISSUE TITLE
Why the datasets is incomplete?

### ISSUE THREAD

**Issue by a86612** [gsndr/CLAIRE#1]
All datasets are downloaded from websites that you provide. I found the datasets incomplete When I ran the code. I will very grateful if you can provide me with a complete data set.

**Comment by gsndr** [comment]
Sorry, the wrong link to the datasets. Thanks for your report.
I updated thel ink to the datasets in the readme file.

I hope that I solved the problem.

**Comment by a86612** [comment]
> Sorry, the wrong link to the datasets. Thanks for your report. I updated thel ink to the datasets in the readme file.
> 
> I hope that I solved the problem.

Thank you very much.

**Comment by a86612** [comment]
> Sorry, the wrong link to the datasets. Thanks for your report. I updated thel ink to the datasets in the readme file.
> 
> I hope that I solved the problem.

Thank you very much.
